### ISSUE TITLE
大佬能写个爱看吗

### ISSUE THREAD

**Issue by w5150** [zhixc/TVJar_test#1]

**Comment by w5150** [comment]
用java写个爱看

**Comment by zhixc** [comment]
抱歉，如果您有需求可以自行编写。

**Comment by w5150** [comment]
大佬爱看详细界面应该怎么写爬不到播放列表

**Comment by zhixc** [comment]
参考 https://github.com/zhixc/TVJar_test/blob/main/app/src/main/java/com/github/catvod/spider/Voflix.java 的 detailContent 方法去写
